Hw2
MariShc/AT pull request #2
Opened 2021-11-24 16:39 UTC by MariShc

Homework 2

2021-11-29 14:37 UTC, diyakov requested changes

2021-11-29 14:37 UTC, diyakov commented on hw2/src/main/java/animals/Wolf.java
> +    }
эти методы у всех животных одинаковые, уносим в базовый класс

2021-11-29 14:37 UTC, diyakov commented on hw2/src/main/java/animals/Carnivore.java
> +        } else {
else тут не нужен, мы же return делаем, можно без него продолжать. и лучше сначала ошибочные ветки обрабатывать и отваливаться, а потом уже просто продолжать основную без else

2021-11-29 14:37 UTC, diyakov commented on hw2/src/main/java/Zoo.java
> +        ArrayList<Animal> pond = new ArrayList<Animal>(Arrays.asList(duck1, duck2, fish1, fish2));
тут косяк, у нас могут быть животные, которые не плавают, я не должен мочь их положить в список pond
дальше там идет какая то странная манипуляция с созданием новых животных. не понимаю зачем, надо убрать :)

2021-11-29 14:37 UTC, diyakov commented on hw2/src/main/java/Worker.java
> +    public void getVoice(Animal animal) {
нарушение условий ДЗ, при попытке передать животное без voice - не должно компилироваться

2021-11-29 14:37 UTC, diyakov commented on hw2/src/main/java/Worker.java
> +            animal.addSatiety();
лучше ответственность за увеличение сытости возложить на метод кормежки. рабочему знать об этом не нужно

2021-12-09 07:30 UTC, Teraule approved these changes

2021-12-09 07:30 UTC, Teraule commented on hw2/src/main/java/animals/Lion.java
> +    }
если метод в каждом животном нужен только ради константы, то ее можно сделать членом класса и назначать в конструкторе, а метод тоже унести в базовый

2021-12-09 21:17 UTC, merged